package:
  name: larray_eurostat
  version: 0.31-dev

source:
  git_tag: 0.31-dev
  git_url: https://github.com/larray-project/larray_eurostat.git
#  git_tag: master
#  git_url: file://c:/Users/gdm/devel/larray_eutostat/.git

build:
  # If this is a new build for the same version, increment the build number
  number: 0
  # we can use this instead of explicit build scripts (bld.bat and build.sh)
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - pip
    - python

  run:
    - python
    - larray

test:
#  requires:
#    - pytest

  imports:
    - larray_eurostat

#  commands:
#    # You can also put a file called run_test.py in the recipe that will be run at test time.
#    - pytest --pyargs larray_eurostat

about:
  home: https://github.com/larray-project/larray_eurostat
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "Additional package to import Eurostat files using LArray"

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen

# See
# https://conda.io/docs/user-guide/tasks/build-packages/index.html
# for more information about meta.yaml
