{% set version = "0.34" %}

package:
  name: larray_eurostat
  version: {{ version }}

source:
  git_tag: {{ version }}
  git_url: https://github.com/larray-project/larray_eurostat.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - larray

test:
  requires:
    - pytest

  imports:
    - larray_eurostat

  commands:
    - pytest --pyargs larray_eurostat

about:
  home: https://github.com/larray-project/larray_eurostat
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Additional package to import Eurostat files using LArray"
  dev_url: http://github.com/larray-project/larray_eurostat

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
